import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { tempDir } from '../platform/paths.mjs';
import { initState, checkpointState, finalizeState } from './state.mjs';

const withDir = (run) => {
  const dir = mkdtempSync(path.join(tempDir(), 'refiner-'));
  try {
    return run(dir);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
};

const stateFile = (root, name) => path.join(root, '.refiner', 'artifacts', name, 'state.json');
const readState = (root, name) => JSON.parse(readFileSync(stateFile(root, name), 'utf8'));

const seedState = (root, name, overrides) => {
  const dir = path.join(root, '.refiner', 'artifacts', name);
  mkdirSync(dir, { recursive: true });
  writeFileSync(
    path.join(dir, 'state.json'),
    JSON.stringify({
      refinement_id: 'prior-id-0001',
      artifact_name: name,
      artifact_type: 'content',
      content_type: 'direct:content',
      current_iteration: 3,
      convergence_status: 'running',
      iteration_history: [],
      ...overrides,
    }),
  );
};

test('a fresh artifact gets state with a generated refinement id', () => {
  const state = withDir((root) => initState({ root, artifactName: 'acme' }));

  assert.equal(state.artifact_name, 'acme');
  assert.match(state.refinement_id, /^[0-9a-f-]{36}$/);
  assert.equal(state.convergence_status, 'running');
  assert.equal(state.current_iteration, 0);
});

test('the refinement id is generated by Node, not uuid.uuid4 via python3', () => {
  const a = withDir((root) => initState({ root, artifactName: 'x' }).refinement_id);
  const b = withDir((root) => initState({ root, artifactName: 'x' }).refinement_id);

  assert.notEqual(a, b);
});

test('timestamps are ISO 8601 UTC, not `date -u` output', () => {
  const state = withDir((root) => initState({ root, artifactName: 'acme' }));

  assert.match(state.started_at, /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/);
  assert.equal(state.started_at, state.updated_at);
});

test('state is written to disk, not only returned', () => {
  const written = withDir((root) => {
    initState({ root, artifactName: 'acme' });
    return existsSync(stateFile(root, 'acme'));
  });

  assert.equal(written, true);
});

// The three branches upstream state-init.sh implements.

test('an existing running artifact RESUMES rather than being truncated', () => {
  const result = withDir((root) => {
    seedState(root, 'acme', { convergence_status: 'running', current_iteration: 3 });
    const state = initState({ root, artifactName: 'acme' });
    return { state, onDisk: readState(root, 'acme') };
  });

  // The prior id and iteration survive: a resume must not destroy progress.
  assert.equal(result.state.refinement_id, 'prior-id-0001');
  assert.equal(result.state.current_iteration, 3);
  assert.equal(result.onDisk.current_iteration, 3);
});

test('a resume refreshes updated_at but leaves started_at alone', () => {
  const state = withDir((root) => {
    seedState(root, 'acme', {
      convergence_status: 'running',
      started_at: '2020-01-01T00:00:00Z',
      updated_at: '2020-01-01T00:00:00Z',
    });
    return initState({ root, artifactName: 'acme' });
  });

  assert.equal(state.started_at, '2020-01-01T00:00:00Z');
  assert.notEqual(state.updated_at, '2020-01-01T00:00:00Z');
});

test('a finalized artifact starts a NEW cycle seeded from the prior state', () => {
  const state = withDir((root) => {
    seedState(root, 'acme', { convergence_status: 'converged', current_iteration: 5 });
    return initState({ root, artifactName: 'acme' });
  });

  assert.notEqual(state.refinement_id, 'prior-id-0001');
  assert.equal(state.prior_refinement_id, 'prior-id-0001');
  assert.equal(state.current_iteration, 0);
  assert.equal(state.convergence_status, 'running');
});

test('checkpoint records an iteration and advances the counter', () => {
  const state = withDir((root) => {
    initState({ root, artifactName: 'acme' });
    return checkpointState({ root, artifactName: 'acme', phase: 'execute', note: 'first pass' });
  });

  assert.equal(state.current_iteration, 1);
  assert.equal(state.iteration_history.length, 1);
  assert.equal(state.iteration_history[0].phase, 'execute');
});

test('finalize sets a terminal convergence status', () => {
  const state = withDir((root) => {
    initState({ root, artifactName: 'acme' });
    return finalizeState({ root, artifactName: 'acme', status: 'converged' });
  });

  assert.equal(state.convergence_status, 'converged');
  assert.ok(state.finalized_at);
});

test('checkpoint on an unknown artifact degrades rather than throwing', () => {
  const result = withDir((root) => checkpointState({ root, artifactName: 'never-initialised' }));

  assert.equal(result.status, 'degraded');
});

// The write goes through lib/platform/atomic-write.mjs: a predictable truncating
// temp path is the data-loss bug this project already fixed once.
test('a bystander file in the state directory is never damaged', () => {
  const survived = withDir((root) => {
    initState({ root, artifactName: 'acme' });
    const bystander = path.join(root, '.refiner', 'artifacts', 'acme', 'important.txt');
    writeFileSync(bystander, 'do not destroy me');
    checkpointState({ root, artifactName: 'acme', phase: 'execute' });
    return readFileSync(bystander, 'utf8');
  });

  assert.equal(survived, 'do not destroy me');
});

test('no module in lib/refiner reads the home directory directly', () => {
  // paths.mjs is the only module allowed to ask the OS where things live.
  const source = readFileSync(new URL('./state.mjs', import.meta.url), 'utf8');

  assert.doesNotMatch(source, /os\.homedir\(\)|process\.env\.HOME|process\.env\.USERPROFILE/);
});
