import { test } from 'node:test';
import assert from 'node:assert/strict';
import { cpSync, existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { tempDir } from '../../lib/platform/paths.mjs';
import { acquireLock } from '../../lib/platform/lock.mjs';

const ROOT = path.resolve(import.meta.dirname, '../..');
const LOCK = 'rules/.build.lock';

// A fixture tree, so the real repository is never written to by a test.
const fixture = (run) => {
  const work = mkdtempSync(path.join(tempDir(), 'build-'));
  try {
    for (const entry of ['rules', 'CLAUDE.md', 'AGENTS.md', '.claude', '.cursor', 'docs', 'lib']) {
      cpSync(path.join(ROOT, entry), path.join(work, entry), { recursive: true });
    }
    rmSync(path.join(work, LOCK), { force: true });
    return run(work);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
};

const build = (cwd, args = []) =>
  execFileSync(process.execPath, ['rules/build.mjs', ...args], { cwd, encoding: 'utf8', stdio: 'pipe' });

test('--check reports every target current on an untouched tree', () => {
  fixture((work) => {
    const output = build(work, ['--check']);

    assert.match(output, /files current/);
  });
});

test('--check detects drift in a generated file', () => {
  fixture((work) => {
    const target = path.join(work, '.claude/rules/rust.md');
    writeFileSync(target, `${readFileSync(target, 'utf8')}\nhand edit\n`);

    assert.throws(
      () => build(work, ['--check']),
      (error) => /drift: \.claude\/rules\/rust\.md/.test(error.stderr),
    );
  });
});

test('a write run restores a drifted file', () => {
  fixture((work) => {
    const target = path.join(work, '.claude/rules/rust.md');
    const original = readFileSync(target, 'utf8');
    writeFileSync(target, 'clobbered');

    build(work);

    assert.equal(readFileSync(target, 'utf8'), original);
  });
});

test('a write run removes a stale generated file and says so', () => {
  fixture((work) => {
    const stale = path.join(work, '.claude/rules/obsolete.md');
    writeFileSync(stale, `---\npaths: ['**/*.x']\n---\n<!-- prometheus-rules: v4 · generated by rules/build.mjs from rules/src/ — edit the source, never this file -->\nbody\n`);

    const output = build(work);

    assert.match(output, /removed {2}\.claude\/rules\/obsolete\.md/);
    assert.ok(!existsSync(stale));
  });
});

test('a write run leaves no lock behind', () => {
  fixture((work) => {
    build(work);

    assert.ok(!existsSync(path.join(work, LOCK)));
  });
});

test('a second concurrent write run is refused and writes nothing', () => {
  fixture((work) => {
    const target = path.join(work, '.claude/rules/rust.md');
    writeFileSync(target, 'clobbered');
    const release = acquireLock(path.join(work, LOCK));

    try {
      assert.throws(
        () => build(work),
        (error) => /lock held/.test(error.stderr),
      );
      assert.equal(readFileSync(target, 'utf8'), 'clobbered', 'the refused run must not have written');
    } finally {
      release();
    }
  });
});

test('--check takes no lock, so it runs while a write holds one', () => {
  fixture((work) => {
    const release = acquireLock(path.join(work, LOCK));

    try {
      assert.match(build(work, ['--check']), /files current/);
    } finally {
      release();
    }
  });
});

test('a RulesBuildError is reported as a one-line message, not a stack trace', () => {
  fixture((work) => {
    // build.conf naming a stack with no source file is the documented RulesBuildError path.
    const conf = path.join(work, 'rules/build.conf');
    writeFileSync(conf, readFileSync(conf, 'utf8').replace('stacks="rust"', 'stacks="rust nosuchstack"'));

    assert.throws(
      () => build(work, ['--check']),
      (error) => {
        assert.match(error.stderr, /no rules\/src\/tech\/<name>\.md: nosuchstack/);
        assert.doesNotMatch(error.stderr, /at .*build\.mjs:\d+/, 'a known error must not print a stack');
        return true;
      },
    );
  });
});
