// Pure rendering of every agent-context target from rules/src/. No file I/O here — build.mjs owns that.
//
//   constitution.md + routing.md          ─▶ CLAUDE.md, and a byte-identical copy per mirror (AGENTS.md…)
//   {tech,domain,project}/*.md            ─▶ .claude/rules/*.md, .cursor/rules/*.mdc, <dir>/AGENTS.md
//   routing.md                            ─▶ docs/skill-routing.md
//
// Node port of the Prometheus pack's v4 build.py. One deliberate difference: mirrors are copies, not
// symlinks, because symlinks need Developer Mode or elevation on Windows.

export const HEADER =
  '<!-- prometheus-rules: v4 · generated by rules/build.mjs from rules/src/ — edit the source, never this file -->';
export const ROUTING_MARK = '<!-- routing:layer0 -->';
export const LIMITS = Object.freeze({ l0Lines: 120, l0Chars: 12_500, ruleLines: 80, nestedLines: 320 });

const RULE_COUNT = 17;
const FOLDERS = ['tech', 'domain', 'project'];

export class RulesBuildError extends Error {}

const countLines = (text) => text.split('\n').length - 1;
const words = (value) => (value ?? '').split(/\s+/).filter(Boolean);

export function parseConf(text) {
  const entries = text
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith('#'))
    .map((line) => {
      const at = line.indexOf('=');
      return [line.slice(0, at).trim(), line.slice(at + 1).trim().replace(/^"|"$/g, '')];
    });
  return Object.fromEntries(entries);
}

export function splitFrontmatter(text, name) {
  // This function is exported and callable without readText, so a CRLF rule file must parse
  // here too — and must return exactly what the LF equivalent returns, carriage returns and
  // all folded away. Matching \r?\n alone would parse but leave \r inside front and body.
  const normalised = text.replace(/\r\n/g, '\n');
  const match = /^---\n([\s\S]*?)\n---\n([\s\S]*)$/.exec(normalised);
  if (!match || !match[1].includes('paths:')) {
    throw new RulesBuildError(`${name} has no \`paths:\` frontmatter — it would load unconditionally`);
  }
  return { front: match[1], body: match[2] };
}

/** One line per table group: **Group:** when → `skill` · when → `skill`. */
export function routingLayer0(routing) {
  const groups = routing.split(/^## /m).slice(1);
  const lines = groups.flatMap((group) => {
    const [title, ...rest] = group.split('\n');
    const rows = rest.filter((row) => row.startsWith('|') && !/^\|\s*-/.test(row));
    if (rows.length < 2) return [];
    const cells = rows.slice(1).map((row) => {
      const [when, invoke, status] = row.replace(/^\||\|$/g, '').split('|').map((cell) => cell.trim());
      return `${when} → ${invoke}${status.includes('absent') ? ' _(absent)_' : ''}`;
    });
    return [`- **${title.trim()}:** ${cells.join(' · ')}`];
  });
  return [
    ...lines,
    '- **No row matches:** `find-skills` → report the top result and its audit status → propose the install; ' +
      'never install unasked. Install commands and notes: `docs/skill-routing.md`.',
  ].join('\n');
}

function cursorGlobs(front) {
  const match = /paths:\s*\[([\s\S]*?)\]/.exec(front);
  if (!match) return '';
  return match[1].split(',').map((glob) => glob.trim().replace(/^['"]|['"]$/g, '')).join(',');
}

function selectRules(rules, stacks) {
  const missing = stacks.filter((stack) => !(`tech/${stack}` in rules));
  if (missing.length) {
    throw new RulesBuildError(`build.conf lists stacks with no rules/src/tech/<name>.md: ${missing.join(', ')}`);
  }
  const keep = ([key]) => !key.startsWith('tech/') || stacks.includes(key.slice('tech/'.length));
  const order = ([a], [b]) => FOLDERS.indexOf(a.split('/')[0]) - FOLDERS.indexOf(b.split('/')[0]) || a.localeCompare(b);
  return Object.fromEntries(Object.entries(rules).filter(keep).sort(order));
}

function nestedFile(directory, keys, selected) {
  const intro = [
    HEADER,
    `# Rules for \`${directory}/\``,
    '',
    'For harnesses without path-scoped rules. The constitution is the root `AGENTS.md` and is not repeated here.',
    '',
  ];
  const bodies = keys.map((key) => {
    if (!(key in selected)) throw new RulesBuildError(`build.conf names unknown source \`${key}\` for ${directory}/`);
    return `${splitFrontmatter(selected[key], key).body.trim()}\n`;
  });
  return [...intro, ...bodies].join('\n');
}

/**
 * @param {{constitution: string, routing: string, rules: Record<string, string>}} sources  keyed `folder/name`
 * @param {Record<string, string>} conf
 * @param {{existingDirs: string[], withCursor?: boolean}} env
 * @returns {{files: Record<string, string>, mirrors: string[]}}
 */
export function render(sources, conf, env) {
  if (!sources.constitution.includes(ROUTING_MARK)) {
    throw new RulesBuildError('constitution.md is missing the routing marker');
  }
  const layer0 = `${HEADER}\n${sources.constitution.replace(ROUTING_MARK, routingLayer0(sources.routing))}`;
  const mirrors = words(conf.mirrors);
  const withCursor = env.withCursor || conf.cursor === 'yes';
  const selected = selectRules(sources.rules, words(conf.stacks));

  const ruleFiles = Object.entries(selected).flatMap(([key, text]) => {
    const name = key.split('/')[1];
    const { front, body } = splitFrontmatter(text, key);
    const claude = [`.claude/rules/${name}.md`, `---\n${front}\n---\n${HEADER}\n${body}`];
    const cursor = [`.cursor/rules/${name}.mdc`, `---\nglobs: ${cursorGlobs(front)}\nalwaysApply: false\n---\n${HEADER}\n${body}`];
    return withCursor ? [claude, cursor] : [claude];
  });

  const nestedFiles = words(conf.nested)
    .map((entry) => entry.split(':'))
    .filter(([directory]) => env.existingDirs.includes(directory))
    .map(([directory, keys]) => [`${directory}/AGENTS.md`, nestedFile(directory, keys.split(','), selected)]);

  const files = Object.fromEntries([
    ['CLAUDE.md', layer0],
    ...mirrors.map((mirror) => [mirror, layer0]),
    ['docs/skill-routing.md', `${HEADER}\n${sources.routing}`],
    ...ruleFiles,
    ...nestedFiles,
  ]);
  return { files, mirrors };
}

export function budgetErrors(files) {
  const layer0 = files['CLAUDE.md'];
  const errors = [];
  const lines = countLines(layer0);
  if (lines > LIMITS.l0Lines) {
    errors.push(`CLAUDE.md is ${lines} lines (limit ${LIMITS.l0Lines}) — apply the placement test, move rules down a layer`);
  }
  if (layer0.length > LIMITS.l0Chars) errors.push(`CLAUDE.md is ${layer0.length} chars (limit ${LIMITS.l0Chars})`);

  const ids = [...layer0.matchAll(/\*\*A-(\d+) ·/g)].map((match) => Number(match[1])).sort((a, b) => a - b);
  const expected = Array.from({ length: RULE_COUNT }, (_, index) => index + 1);
  if (ids.join() !== expected.join()) {
    errors.push(`CLAUDE.md must carry A-1…A-${RULE_COUNT} exactly once each; found ${JSON.stringify(ids)}`);
  }

  for (const [path, text] of Object.entries(files)) {
    if (text === layer0) continue; // CLAUDE.md itself and its byte-identical mirrors
    const count = countLines(text);
    if (path.startsWith('.claude/rules/') && count > LIMITS.ruleLines + 1) {
      errors.push(`${path} is ${count} lines (limit ${LIMITS.ruleLines}) — split the rule or move detail to Layer 3`);
    }
    if (path.endsWith('/AGENTS.md') && count > LIMITS.nestedLines) {
      errors.push(`${path} is ${count} lines (limit ${LIMITS.nestedLines})`);
    }
    if (/^\s*-?\s*\*\*A-\d+ ·/m.test(text)) errors.push(`${path} repeats constitution rule IDs — duplicate constitution`);
  }
  return errors;
}
