import fs from 'node:fs';import crypto from 'node:crypto';import {dispatchJudge} from '/Users/gqadonis/.codex/worktrees/bossfang-uar-architecture/prometheus-skills-mini/lib/review/judge-client.mjs';import {extractJsonFromCompletion,normalizeFindings} from '/Users/gqadonis/.codex/worktrees/bossfang-uar-architecture/prometheus-skills-mini/lib/review/judge-findings.mjs';
const d="/Users/gqadonis/.codex/worktrees/bossfang-uar-architecture/prometheus-skills-mini/workstreams/bossfang-uar-architecture/.kbd-orchestrator/phases/bossfang-uar-authorization-and-execution",p="/Users/gqadonis/.codex/worktrees/bossfang-uar-architecture/prometheus-skills-mini/workstreams/bossfang-uar-architecture",out=d+'/review/execute-design';fs.mkdirSync(out,{recursive:true});
const roots=['/Users/gqadonis/.claude/worktrees/bauar-bossfang/workstreams/bauar/openspec/changes/bossfang-bauar-harness-delegation','/Users/gqadonis/.claude/worktrees/bauar-bossfang/workstreams/bauar/openspec/changes/bossfang-bauar-mcp-attribution'];
const files=[d+'/execute-scope-amendment.md',d+'/execution-bindings.json',d+'/evidence/execute/bossfang-prerequisites.md',p+'/openspec/changes/bauar-03-harness-delegation/design.md',p+'/openspec/changes/bauar-03-harness-delegation/specs/job-harness-delegation/spec.md'];
for(const root of roots){for(const file of ['design.md','proposal.md','tasks.md','execution-scope.json'])files.push(root+'/'+file);for(const sub of fs.readdirSync(root+'/specs')) files.push(root+'/specs/'+sub+'/spec.md');}
const packet={purpose:'Independent review of material repository-specific design refinement before product dispatch; not partial code QA.',producer_model:'unknown',source_workers:'gpt-6-astra/high native Codex; driver identity unknown',user_requirements:'One authoritative UAR agent loop per delegated Bossfang attempt, exact approval/run/owner binding; all reachable retry/wake/cancel paths; separate actual local/remote evidence; user explicitly chose unsupported/unknown restart + reconciliation, strict owned-client cutover, no external receivers/IdP/new custody and remove runtime defaults. No production changes yet in this Bossfang worktree.',artifacts:files.map(path=>({path,content:fs.readFileSync(path,'utf8')}))};fs.writeFileSync(out+'/packet.json',JSON.stringify(packet,null,2));
const system=fs.readFileSync('/Users/gqadonis/.codex/worktrees/bossfang-uar-architecture/prometheus-skills-mini/skills/adversarial-review/assets/reviewer-mandate-artifact.md','utf8')+'\nFocus on correctness of residual reuse, atomic storage and recovery, no duplicate loops/effects, concrete ownership and implementability, and source-vs-assumption limits. Do not ask for broad tests before production. Distinguish material missing invariants from optional enhancements. Review these artifacts independently, no generation history. Return findings JSON only.';
const baseUrl=process.env.LITER_LLM_BASE_URL;if(!baseUrl)throw Error('Existing gateway URL unavailable');
const raw=await dispatchJudge({baseUrl,authToken:process.env.LITER_LLM_MASTER_KEY||process.env.OPENAI_API_KEY||'sk-local',model:'MiniMax-M3',system,packet:JSON.stringify(packet),maxAttempts:1,initialTimeoutMs:300000});
const cleaned=raw.replace(/<think>[\s\S]*?<\/think>/g,'').trim();
const normalized=normalizeFindings(extractJsonFromCompletion(cleaned),{mode:'artifact',judgeModel:'MiniMax-M3',producer:'unknown',endpoint:baseUrl});
fs.writeFileSync(out+'/findings.json',JSON.stringify(normalized,null,2)+'\n');fs.writeFileSync(out+'/receipt.json',JSON.stringify({at:new Date().toISOString(),model:'MiniMax-M3',producerCanonicalIdentity:'unknown',crossModelCheck:'unverified-producer-unknown',packetSha256:crypto.createHash('sha256').update(JSON.stringify(packet)).digest('hex'),scope:'design refinement only'},null,2)+'\n');console.log(JSON.stringify(normalized));

