import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import cp from 'node:child_process';
const p="/Users/gqadonis/.codex/worktrees/bossfang-uar-architecture/prometheus-skills-mini/workstreams/bossfang-uar-architecture",s="/Users/gqadonis/.codex/worktrees/bossfang-uar-architecture/prometheus-skills-mini/workstreams/bossfang-uar-architecture/.kbd-orchestrator/phases/bossfang-uar-authorization-and-execution/children/desktop-mcp-projection-acceptance",e="/Users/gqadonis/.codex/worktrees/bossfang-uar-architecture/prometheus-skills-mini/workstreams/bossfang-uar-architecture/.kbd-orchestrator/phases/bossfang-uar-authorization-and-execution/evidence/execute/parent-resume-2026-10-08",old=s+'/evidence/execute',phase='bossfang-uar-authorization-and-execution';
const read=f=>JSON.parse(fs.readFileSync(f,'utf8')),write=(f,j)=>fs.writeFileSync(f,JSON.stringify(j,null,2)+'\n'),hash=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');
const excluded=new Set(['tests/bauar_session_owner.rs','src/uar/mcp_server.rs']),manifest=read(old+'/final-source-manifest-17.json');
const checks=[];for(const repo of manifest.records)for(const f of repo.files){if(repo.name==='uar'&&excluded.has(f.file))throw Error('Excluded path in inventory; no read performed');checks.push({repository:repo.name,file:f.file,matches:hash(path.join(repo.root,f.file))===f.sha256});}
const normal=read(old+'/final-artifact-manifest-17.json'),gate=read(old+'/final-instrumented-artifact-manifest-17.json'),request=read(old+'/G2-postack-02-request.json');
const artifacts=[{file:normal.sidecar.staged,sha256:normal.sidecar.sha256},{file:normal.storageFixture.staged,sha256:normal.storageFixture.sha256},{file:normal.bossBundle.path,sha256:normal.bossBundle.sha256}];
for(const f of normal.resources)artifacts.push({file:path.join(path.dirname(normal.sidecar.staged),f.path),sha256:f.sha256});
artifacts.push({file:path.join(path.dirname(normal.sidecar.staged),'payload-manifest.json'),sha256:normal.payloadManifestSha256});
for(const f of gate.files)artifacts.push({file:path.join(path.dirname(request.env.THE_BOSS_UAR_POST_ACK_SIDECAR_PATH),f.path),sha256:f.sha256});
const bm=read(old+'/G2-postack-02-prelaunch-binding.json');artifacts.push({file:bm.gateArtifactManifest.path,sha256:bm.gateArtifactManifest.sha256});
const artifactChecks=artifacts.map(f=>({...f,matches:hash(f.file)===f.sha256}));
const result={time:new Date().toISOString(),sourceManifestSha256:hash(old+'/final-source-manifest-17.json'),sourceChecks:checks,artifactChecks,sourceCount:checks.length,sourceDrift:checks.filter(x=>!x.matches),artifactDrift:artifactChecks.filter(x=>!x.matches),exclusions:[...excluded],emission:{ordinary:'source12',instrumented:'source13',applicability:'source17 scoped rebinding'},freshBuildClaimed:false};
write(e+'/prelaunch-binding.json',result);if(result.sourceDrift.length||result.artifactDrift.length)throw Error('Source/artifact drift');
const stateR=cp.spawnSync('prometheus',['kbd','--path',p,'status','--json'],{encoding:'utf8',maxBuffer:20000000});const st=JSON.parse(stateR.stdout);const task=st.phases[phase].changes['bauar-04-resource-credential-lifecycle'].tasks['9'];if(st.activePath.phaseId!==phase||task.status!=='in_progress')throw Error('Resume task identity mismatch');
write(e+'/task-resume.json',{time:new Date().toISOString(),revision:st.revision,phase,change:'bauar-04-resource-credential-lifecycle',taskId:'9',status:task.status,title:task.title,existingTaskResumed:true,newCompletionClaimed:false});
const args=['kbd','--path',p,'stage','enter','--command-id','bauar-parent-execute-resume-20261008','--phase',phase,'--id','execute','--title','Execute approved authorization and harness changes with agent teams','--sequence','5'];const stage=cp.spawnSync('prometheus',args,{encoding:'utf8',maxBuffer:20000000});write(e+'/stage-resume.json',{time:new Date().toISOString(),exitCode:stage.status,diagnostic:stage.status?stage.stderr:null});if(stage.status)throw Error('Stage resume failed');
request.id='G2-parent-resume';request.argv=['--import','tsx','scripts/gates/bauar-secret-projection.ts',e+'/G2-13-finite-evidence.json'];request.receipt=e+'/G2-13-command-receipt.json';request.when='Parent task04/9 failed aggregate gate retry after completed child delivery; corrected existing payload13 and source17, no code changes.';write(e+'/G2-13-request.json',request);
console.log(JSON.stringify({sourceCount:checks.length,artifactCount:artifactChecks.length,sourceDrift:result.sourceDrift.length,artifactDrift:result.artifactDrift.length,task:'04/9',status:task.status,request:e+'/G2-13-request.json'}));

