import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {spawnSync} from 'node:child_process';
const out="/Users/gqadonis/.codex/worktrees/bossfang-uar-architecture/prometheus-skills-mini/workstreams/bossfang-uar-architecture/.kbd-orchestrator/phases/phase-bauar-release-acceptance/evidence/assess/baseline.json";
const roots={uar:'/Users/gqadonis/.claude/worktrees/bauar-release-uar',boss:'/Users/gqadonis/.claude/worktrees/bauar-release-boss',bossfang:'/Users/gqadonis/.claude/worktrees/bauar-release-bossfang'};
const selected={uar:['src/uar/api/full_harness.rs','mcp.json'],boss:['src/main/ai/runtime/uar/UarToolApprovalController.ts','build/local-uar-source.json'],bossfang:['crates/librefang-kernel/src/kernel/uar_harness/admission.rs','crates/librefang-kernel/src/kernel/uar_harness/lifecycle.rs']};
function git(root,args){const r=spawnSync('git',args,{cwd:root,encoding:'utf8',shell:false});if(r.status!==0)throw new Error('git command failed');return r.stdout.trim();}
async function digest(file){const hash=crypto.createHash('sha256');for await(const chunk of fs.createReadStream(file))hash.update(chunk);return hash.digest('hex');}
const repositories=Object.fromEntries(Object.entries(roots).map(([id,root])=>[id,{root,head:git(root,['rev-parse','HEAD']),selectedStatus:git(root,['status','--porcelain=v1','--',...selected[id]]),selectedPaths: selected[id]}]));
const app=roots.boss+'/dist/mac-arm64/The Boss.app';
const files=[app+'/Contents/Resources/app.asar',app+'/Contents/Resources/app.asar.unpacked/resources/binaries/darwin-arm64/uar-sidecar',app+'/Contents/Resources/app.asar.unpacked/resources/binaries/darwin-arm64/.uar-local-payload.json',"/Users/gqadonis/.codex/worktrees/bossfang-uar-architecture/prometheus-skills-mini/workstreams/bossfang-uar-architecture/.kbd-orchestrator/phases/phase-bauar-release-integration-2026-10-09/evidence/execute/local-delivery.json"];
const artifacts=[];for(const file of files){const st=fs.statSync(file);artifacts.push({file,bytes:st.size,sha256:await digest(file)});}
const runner="/Users/gqadonis/.codex/worktrees/bossfang-uar-architecture/prometheus-skills-mini/workstreams/bossfang-uar-architecture/.kbd-orchestrator/phases/phase-bauar-release-integration-2026-10-09/acceptance/local-release-intake.mjs";
const r={schemaVersion:1,at:new Date().toISOString(),phase:'phase-bauar-release-acceptance',kind:'static-assessment-inventory',repositories,artifacts,appExists:fs.statSync(app).isDirectory(),plannedAcceptanceRunner:{path:runner,exists:fs.existsSync(runner)},productTestsRun:false,productBuildsRun:false,productLaunchRun:false,excludedF6FilesAccessed:false,scope:'Only named files and Git refs; not a full repository cleanliness or source-to-bundle claim'};
fs.writeFileSync(out,JSON.stringify(r,null,2)+'\n');console.log(JSON.stringify(r,null,2));
