// Port of shared/lib/runtime-authority.sh (prometheus-skill-pack, 31 lines).
//
// Source behaviour: a waypoint is "runtime-authoritative" once its `generatedBy` field says
// `kbd-runtime` — from that point on, only the canonical `prometheus kbd` CLI may mutate the
// projection, and a direct write must be rejected. The mini has no native writer yet (only
// `lib/doctor/kbd.mjs`, which reads), so the guard's job today is narrower than the source: it
// still answers "is this projection runtime-owned", but does not yet reference a mini-native
// replacement command, because none exists. Callers that gain their own write path (kbd-apply,
// kbd-new-phase, etc., ported later in this phase) call `assertProjectionWritable` before writing
// `.kbd-orchestrator/current-waypoint.json` or `progress.json` directly.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { tempDir } from '../platform/paths.mjs';
import { isRuntimeAuthoritative, assertProjectionWritable } from './runtime-authority.mjs';

const repo = (waypoint) => {
  const root = mkdtempSync(path.join(tempDir(), 'runtime-authority-'));
  if (waypoint !== undefined) {
    mkdirSync(path.join(root, '.kbd-orchestrator'), { recursive: true });
    writeFileSync(path.join(root, '.kbd-orchestrator', 'current-waypoint.json'), waypoint);
  }
  return { root, dispose: () => rmSync(root, { recursive: true, force: true }) };
};

test('a waypoint generated by kbd-runtime is authoritative', () => {
  const r = repo(JSON.stringify({ generatedBy: 'kbd-runtime' }));
  try {
    assert.equal(isRuntimeAuthoritative(r.root), true);
  } finally {
    r.dispose();
  }
});

test('a waypoint with a different generatedBy is not authoritative', () => {
  const r = repo(JSON.stringify({ generatedBy: 'something-else' }));
  try {
    assert.equal(isRuntimeAuthoritative(r.root), false);
  } finally {
    r.dispose();
  }
});

test('an absent waypoint is not authoritative', () => {
  const r = repo();
  try {
    assert.equal(isRuntimeAuthoritative(r.root), false);
  } finally {
    r.dispose();
  }
});

test('malformed JSON in the waypoint is not authoritative, not a thrown error', () => {
  const r = repo('{not json');
  try {
    assert.equal(isRuntimeAuthoritative(r.root), false);
  } finally {
    r.dispose();
  }
});

test('assertProjectionWritable throws naming the target when the runtime owns it', () => {
  const r = repo(JSON.stringify({ generatedBy: 'kbd-runtime' }));
  try {
    assert.throws(
      () => assertProjectionWritable(r.root, 'current-waypoint.json'),
      /current-waypoint\.json/
    );
  } finally {
    r.dispose();
  }
});

test('assertProjectionWritable is silent when the runtime does not own the projection', () => {
  const r = repo();
  try {
    assert.doesNotThrow(() => assertProjectionWritable(r.root, 'current-waypoint.json'));
  } finally {
    r.dispose();
  }
});
