import fs from 'node:fs';import cp from 'node:child_process';import crypto from 'node:crypto';
import {hooksFire} from '/Users/gqadonis/.codex/worktrees/bossfang-uar-architecture/prometheus-skills-mini/lib/kbd/hooks.mjs';import {runHookCommand} from '/Users/gqadonis/.codex/worktrees/bossfang-uar-architecture/prometheus-skills-mini/lib/kbd/hook-command.mjs';
const p="/Users/gqadonis/.codex/worktrees/bossfang-uar-architecture/prometheus-skills-mini/workstreams/bossfang-uar-architecture",s="/Users/gqadonis/.codex/worktrees/bossfang-uar-architecture/prometheus-skills-mini/workstreams/bossfang-uar-architecture/.kbd-orchestrator/phases/bossfang-uar-authorization-and-execution/children/desktop-mcp-projection-acceptance",b="/Users/gqadonis/.codex/worktrees/bossfang-uar-architecture/prometheus-skills-mini/workstreams/bossfang-uar-architecture/.kbd-orchestrator/phases/bossfang-uar-authorization-and-execution",phase='bossfang-uar-authorization-and-execution::desktop-mcp-projection-acceptance',parent='bossfang-uar-authorization-and-execution',e=s+'/evidence/child-exit';
fs.mkdirSync(e,{recursive:true});const read=f=>JSON.parse(fs.readFileSync(f,'utf8')),write=(f,j)=>fs.writeFileSync(f,JSON.stringify(j,null,2)+'\n'),hash=v=>crypto.createHash('sha256').update(v).digest('hex');
const status=()=>{const r=cp.spawnSync('prometheus',['kbd','--path',p,'status','--json'],{encoding:'utf8',maxBuffer:20000000});if(r.status)throw Error('Canonical status unavailable');return JSON.parse(r.stdout);};
const before=status(),ph=before.phases[phase];if(before.activePath.phaseId!==phase||ph.status!=='complete'||ph.stages.reflect.status!=='complete')throw Error('Child completion/active position mismatch');
for(const f of ['phase-guard-pre-retry.json','phase-guard-post.json'])if(read(s+'/evidence/reflect/'+f).exitCode!==0)throw Error('Reflect guard not passed');
const integrity=read(s+'/evidence/reflect/final-report-integrity.json');if(hash(fs.readFileSync(s+'/reflection.md'))!==integrity.reportSha256)throw Error('Reflection changed since screen');
const ap=read(s+'/approval-policy.json');ap.approvals.push({stage:'child-exit',at:new Date().toISOString(),source:'Operator: Approve child exit'});ap.pendingApprovalFor=null;write(s+'/approval-policy.json',ap);
const args=['kbd','--path',p,'phase','activate','--command-id','bauar05-child-exit-approved-20261008','--id',parent,'--exact-next-work','Reconcile desktop child handoff into existing parent acceptance tasks; preserve partial goals and independent release gates.'];
const act=cp.spawnSync('prometheus',args,{encoding:'utf8',maxBuffer:20000000});write(e+'/parent-activate.json',{time:new Date().toISOString(),argv:args,exitCode:act.status,outputSha256:hash(act.stdout??''),diagnostic:act.status?act.stderr:null});if(act.status)throw Error('Parent activation failed');
const runs=[];await hooksFire('child','after',phase,2,2,{orchestratorRoot:'/Users/gqadonis/.codex/skills/kbd-process-orchestrator',cwd:p,phasePath:phase,childPath:'desktop-mcp-projection-acceptance',sourceTool:'kbd-child-exit',runCommand:async(command,env,ctx)=>{const z=await runHookCommand(command,env,ctx);runs.push({status:z.status,skippedUnsupportedShell:String(z.stderr).includes('requires shell semantics')});return z;}});
const after=status(),wp=read(p+'/.kbd-orchestrator/current-waypoint.json'),progress=read(b+'/progress.json');
const counters=st=>Object.values(st.phases[parent].changes).map(c=>({id:c.id,status:c.status,complete:Object.values(c.tasks).filter(t=>t.status==='complete').length,total:Object.keys(c.tasks).length}));
const parentUnchanged=JSON.stringify(counters(before))===JSON.stringify(counters(after));if(!parentUnchanged)throw Error('Unexpected parent task status mutation');
const result={time:new Date().toISOString(),beforeRevision:before.revision,canonicalRevision:after.revision,activePhase:after.activePath.phaseId,path:wp.path,childStatus:after.phases[phase].status,childRollup:progress.children,parentChanges:counters(after),parentTasksUnchanged:parentUnchanged,phaseCompletionAndPhaseAfterRepeated:false,childAfterHooks:runs,memoryPublicationClaimed:false,childExited:after.activePath.phaseId===parent,productEdits:[],testsRun:[],handoffSha256:hash(fs.readFileSync(s+'/handoff-out.md')),reflectionSha256:integrity.reportSha256};
write(e+'/completion.json',result);if(!result.childExited)throw Error('Parent not restored');console.log(JSON.stringify(result));

